default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: JacquesOverflow_development

test:
  <<: *default
  database: JacquesOverflow_test

production:
  <<: *default
  database: JacquesOverflow_production
  username: JacquesOverflow
  password: <%= ENV['JACQUESOVERFLOW_DATABASE_PASSWORD'] %>
